# server/Dockerfile.dev
FROM node:18-alpine
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

# پورت سرور Express
EXPOSE 5000

# دستور اجرای dev با nodemon
# سورس کد بعداً مپ می‌شود
CMD ["npm", "run", "dev"]