-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "acneType" TEXT,
ADD COLUMN     "activeIngredients" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "ageRange" TEXT,
ADD COLUMN     "climate" TEXT,
ADD COLUMN     "currentRoutineProducts" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "dietHabits" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "environmentType" TEXT,
ADD COLUMN     "eyeConcerns" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "isPregnantOrNursing" BOOLEAN,
ADD COLUMN     "knownAllergies" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "medications" TEXT,
ADD COLUMN     "routineComplexity" TEXT,
ADD COLUMN     "skinSensitivity" TEXT,
ADD COLUMN     "sleepHours" TEXT,
ADD COLUMN     "smokingHabit" TEXT,
ADD COLUMN     "stressLevel" TEXT,
ADD COLUMN     "texturePreferences" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "waterIntake" TEXT;
